version: "3.8"

#networks:
#  default:
#    name: localstack-net

services:
  tfrunner:
    build:
      context: ./tfrunner/
      dockerfile: ./Dockerfile
    container_name: tfrunner-cnt
    tty: true
    volumes:
      - type: bind
        source: ./terraform
        target: /mnt/terraform
  localstack:
    image: localstack/localstack
    environment:
      - DOCKER_HOST=tcp://dind:2375
    ports:
      - "4566:4566"
      - "4571:4571"
    depends_on:
      - dind

  dind:
    image: docker:20.10.7-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    volumes:
      - dind-storage:/var/lib/docker
    ports:
      - "2375:2375"

volumes:
  dind-storage: